#! /bin/sh

sxhkd &

bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config border_width     1
bspc config window_gap      12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config top_padding 24
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0

#colors
bspc config active_border_color     '#ebdbb2'
#bspc config focused_border_color    '#458588' #blue
bspc config focused_border_color    '#98971a' #green
bspc config normal_border_color     '#b2282828'
bspc config presel_border_color     '#d79921'
bspc config urgent_border_color     '#cc241d'

bspc monitor -d term web ssh code files vm music
#bspc monitor -d 1 2 3 4 5 6
#bspc monitor -d -I- -II- -III- -IV- -V- -VI-
#bspc monitor -d ▀▄ ▀▄ ▀▄ ▀▄

bspc rule -a brave desktop=^2
bspc rule -a Gimp desktop=^4 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a XCalc state=floating
bspc rule -a Nitrogen state=floating

thunar --daemon &
#tint3 &
#/home/stephen/.local/bin/panel &
#panel &
polybar -r top &
dunst &
#pasystray &
#connman-ui-gtk &
nextcloud &
#nm-applet --sm-disable &
#cbatticon
